#!/bin/bash

function usage () {

echo Error: $*	# print error message supplied as arguments, then canned usage
echo '
mkshdr - make EZID shoulders and minters for ARK and, optionally, DOI

   Usage:  mkshdr [-d] [-u Userid] UILabel [Boulder]

where UILabel is an organization name (eg, "Acme Rocket") to appear in the
EZID user interface next to the shoulder (eg, "Acme Rocket ARKs").  The
optional Boulder, a combination of bow (NAAN) and shoulder, is one of

   NAAN/shoulder   eg, 85067/p2  # shoulders follow first digit convention
   NAAN/           eg, 85067/    # empty shoulder ok; minter will be generated
   NAAN/-          eg, 85067/-   # a shoulder and minter will be generated
   -/shoulder      eg, -/z4      # "-" means the NAAN will be generated
   NAAN            eg, b5067     # empty shoulder; no minter will be generated

If a given NAAN is of the form "bNNNN", only DOI shoulders/minters will be
affected.  A NAAN of bNNNN is synonymous with the DOI prefix 10.NNNN.

The Boulder argument defaults to "-/-".  The "first digit" convention means
the shoulder is a sequence of one or more letters ending with a digit.
Shoulder letters should come from the same "betabetic" repertoire that noid
uses to generate ids with check characters, which includes all alphabetic
letters except {aeiouyl}.

Use -d to generate not only an ARK shoulder but also a DOI shoulder.
Use -u Userid if the shoulder is being created on behalf of an EZID user.
'
}

doi=0 uid=
while [[ ${#*} > 0 ]]
do
	case $1 in
	-d)	doi=1 ; shift ;;
	-u)	uid=$2 ; shift 2 
		if [[ $uid == "" ]]; then
			usage Missing userid ; exit 1
		fi ;;
	-*)	usage Unrecognized option $1; exit 1 ;;
	*)	break ;;
	esac
done
if [[ ${#*} > 2 ]]	# if there are any remaining arguments
then
	usage Too many arguments; exit 1
fi

uilabel=$1
if [[ $uilabel == "" ]]
then
	usage Missing user interface label; exit 1
fi

boulder=${2:-"-/-"}
if [[ $boulder =~ "/.*/" ]]		# if more than one /, error
then
	usage "Boulder ($boulder) must be of the form 'NAAN/shoulder'"
	exit 1
fi
if [[ ! $boulder =~ "/" ]]		# if no /, add one at the end
then
	boulder="$boulder/"
fi

if [[ $boulder =~ "^/" ]]
then
	usage "Empty NAAN.  A NAAN must be of the form '^[1-9b][0-9]{4}$'"
	exit
fi
# split boulder into naan and shdr by assigning to $1 and $2
set - $(echo $boulder | sed 's,/, ,')
naan=$1 shdr=$2
if [[ ! $naan =~ "^(-|[1-9b][0-9]{4})$" ]]
then
	usage "NAAN ($naan) must be of the form '^[1-9b][0-9]{4}$'"
	exit
fi
if [[ $shdr != "" && ! $shdr =~ "^(-|[bcdfghjkmnpqrstvwxz]{1,}[0-9])$" ]]
then
	usage "Shoulder ($shdr) must be empty or of the form" \
		"'^[bcdfghjkmnpqrstvwxz]{1,}[0-9]$'"; exit
fi

echo $uilabel ARKs and DOIs, boulder is $boulder
echo naan is $naan, shoulder is $shdr

ncmd=/noid/nd/noid			# noid command
doipminter=/noid/naans/forge_doip	# doi prefix minter
shdrminter=/noid/naans/forge_shdr	# shoulder minter

echo under construction -- ending prematurely
exit 1

if [[ $naan == "-" ]]
then
	if [[ $doi == 1 ]] then

		# Mint a DOI prefix
		doip=$(/noid/naans/forge/mint_doip)
		if [[ $? != 0 ]]
		then
			echo $doip	# in this case it's a message
			exit 1
		fi

		# Now transform the DOI prefix into a NAAN, if you can;
		# change initial 'b' to '8' to get corresponding ARK NAAN.
		naan=$(echo $doip | sed 's/^b/8/')
		any=$(grep $naan /noid/naans/master_naans)
		if [[ $any != "" ]]
		then
			echo Error: $naan appears to be taken.  Found this:
			echo $any
			exit 1
		fi
	else

		# Mint a NAAN
		/noid/naans/forge/naan_rec $acronym $site $uilabel
		/noid/naans/forge/mint_shdr
		gen_and_set_naan
	fi

if [[ $naan =~ "^b" ]]			# if no ARK ops, just DOI ops
then
	noark=1
fi

exit 0

function gen_doip_and_set_naan () {
	msg=$($ncmd -f $doipminter mint 1 | sed 's/id: //')
	if [[ ! $msg =~ "b[0-9]{4}" ]]
	then
		echo "Generated bad DOI prefix ($msg)"
		exit 1
	fi
	naan=$msg		# returns side-effect
}

function gen_and_set_naan () {
	msg=$(/noid/naans/forge/naan_rec xxxxxx')
	naan=$(echo $prefix | sed 's/id: //')
}

#if [[ $doi == 1 ]]
#then
#	prefix=$($ncmd -f $doipminter mint 1 | sed 's/id: //')
#	naan=$(echo $prefix | sed 's/id: //')
#fi
#$ncmd -f $shdrminter

#naan1?noid - << 'eof'
#bind set $i naan: xxx
#'eof'

#shdr1?noid - << 'eof'
#bind set $i uilabel: xxx
#'eof'

