#!/bin/bash

# This script will be called by prep_shdr and make_shdr.

function usage {

echo '
shdr_exists - check given shoulder name for an existing minter

   Usage:  shdr_exists shdr

Returns 0 (success) if there is a minter and prints whatever was found.
Returns 1 (non-success) if no minter was found; this is usually what you
want before proceeding to create a minter.
';
}

shdr=$1
[[ "$shdr" == '' ]] && {
	usage
	exit 0		# because this is the unexpected return status
}

# checks for a minter # XXX does it work?
#any=$(grep -w $shdr /noid/naans/master_shoulders | grep -v nd/noid)
any=$( egrep '^minter:|^::' /noid/shoulders/master_shoulders.txt |
		grep -i "d/noidu_$shdr" | grep -v nd/noid )
[[ $any == "" ]] && {
	#echo $shdr
	exit 1		# probably what the caller wants to see
}

#echo Error: $shdr might be taken.  Here is what I found:
echo Note: $shdr might be taken.  Here is what I found:
echo $any
exit 0
