#! /bin/bash
sourcedir=`dirname $0`

deliverydir=$HOME/sv/cur/apache2/htdocs/e/pop/ezid

# Backup from old copy
cp -p $deliverydir/master_shoulders.txt $sourcedir/master_shoulders.txt.bak

# Push to place where EZID will pick it up.
# xxx kludge -- for now, copy to read-protected area for just "ezid" populator;
#               what about later for other populators (eg, oca)?
#
cp -p $sourcedir/master_shoulders.txt $deliverydir

# Copy to place where external prefix harvesters can pick it up w.o. creds.

cp -p $sourcedir/master_shoulders.txt $HOME/sv/cur/apache2/htdocs/e/pub/
