#!/bin/csh -f

if ($# < 2) then
	echo "Usage:   $0 Acronym InstitutionName"
	echo "Example:"
	echo ""
	echo "    $ $0 OU 'Oaksterdam University'"
	echo "    00001/98765: OU        2010.04.09   # Oaksterdam University"
	echo ""
	echo "which you copy onto the end of the 'grandfathered' file."
	echo "See also naan_gen."
	exit 1
endif

set acro = "$1"
set institution = "$2 $3 $4 $5 $6 $7 $8 $9"

set ndcmd = "noid mint 1"
#set ndcmd = "echo id: 00001/8999a"

set id = `$ndcmd | sed 's,^id: ,,'`
set partial = `echo $id | sed 's,^00001/,,'`

# Criteria go here.
if ("$partial" =~ "9*" || "$partial" =~ "0*") then
	echo ECHO noid hold set $id
	noid hold set $id
	echo "Skipping id: $id".  Try again.
	exit 1
endif

printf "${id}: %-9s `date +%Y.%m.%d`   # $institution\n" $acro


# % noid dbcreate .rddddd long 00001 n2t.info naan
# Created:   minter for 100000 random identifiers of form .rddddd
#        A Noid minting and binding database has been created that will bind
#        and mint 100,000 identifiers with the template ".rddddd".
#        Sample identifiers would be "00001/79953" and "00001/22939".
#        Minting order is random.  See ./NOID/README for details.

# % noid hold set `sed 's/:.*//' grandfathered`
# # test with
# % noid mint 100000

# -----
# Going forward, mint as usual but prepare to filter out unwanted NAANs.
# For example, if for a NANN starting with 0 or containing too many repeated
# digits, do
# 
# % noid mint 1
# id: 00001/01234
# 
# % noid hold set 00001/01234
# 
# % noid mint 1
# ...   <repeat as necessary>
# 
# Then record the assignment you choose back into "grandfathered" just in
# case we have to start over again.
