#!/bin/bash

# This script will be called by shdr_prep.

function usage {

echo Error: $*	# print error message supplied as arguments, then canned usage
echo '
mint_shdr - mint a shoulder (from a minter recycle queue)

   Usage:  mint_shdr [ mint | unmint shoulder ... ]

Use "unmint" to return shoulders back to a FIFO queue for reminting.
';
}

ncmd=/noid/nd/noid			# noid command (old noid)
shdrminter=/noid/naans/forge_shdr	# shoulder minter

if [[ $1 == "unmint" ]]
then
	shift
	# XXXX likely bug! why doesn't unminting then minting work??
	#      try with "now" and "first"
	$ncmd -f $shdrminter queue first $*
	exit $?

elif [[ $1 != "mint" ]]
then
	usage please specify the mint or unmint command
	exit
fi

msg=$($ncmd -f $shdrminter mint 1 | sed 's/id: //')
if [[ ! $msg =~ ^([bcdfghjkmnpqrstvwxz]{1,}[0-9])$ ]]
then
	echo "Generated bad shoulder ($msg)"
	exit 1
fi
shdr=$msg

./shdr_exists $shdr &&
	exit 1

echo $shdr		# success: print shoulder
exit 0
