#!/usr/bin/perl

use 5.006;
use strict;
use warnings;

# Author:  John A. Kunze, jak@ucop.edu, California Digital Library
# Copyright (c) 2013-2014 UC Regents

# xxx ### To be run from /noid/naans/forge.

# main
{
	system 'sed -n "/=== Add new shoulders/,\$p" '
		#. '/noid/naans/master_shoulders | head -23';
		. '../master_shoulders.txt '
		. '| egrep "^::|^datacenter" | head -20';
	print '
=======================================
Reviewing the above, enter your estimate of the next prefix and shoulders
as arguments to "shdr_prep", following these regexps:

	./shdr_prep [bc]\\d\\d\\d\\d [b-z]+\\d [b-z]+\\d

where you can specify "-" instead of the ARK or DOI shoulder
if you do not want to create a minter on the respective shoulder.
';
}
